services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: myapp
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            - db
    
    db:
        image: mysql:8.0
        container_name: docker-demo-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: server
        volumes:
            - db_data:/var/lib/mysql
            
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db_data: