# 성능 측정용 DB
version: '3.8'

services:
    mysql-test:
        image: mysql:8.0
        container_name: perf-mysql-test
        command: ["--local-infile=1"]
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: testdb
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3307:3306"            # 로컬 개발용과 포트 분리
        volumes:
            - ./src/test/resources/db/init:/docker-entrypoint-initdb.d
            - ./src/test/resources/db/local.cnf:/etc/mysql/conf.d/local.cnf:ro