spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                use_sql_comments: true
                show_sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            auto-commit: true

cloud:
    aws:
        region: ap-northeast-2
        s3:
            bucket-name: ${S3_BUCKET_NAME}
            access-key: ${S3_ACCESS_KEY}
            secret-key: ${S3_SECRET_KEY}

logging:
    level:
        root: INFO
        org.springframework.core.env: DEBUG
jwt:
    secret:
        key: ${JWT_SECRET}