spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                use_sql_comments: true
                show_sql: true
        hibernate:
#            ddl-auto: create
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL:jdbc:mysql://localhost:3306/server?serverTimezone=Asia/Seoul}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:1234}
        hikari:
            auto-commit: true

logging:
    level:
        root: INFO
        org.springframework.core.env: DEBUG
jwt:
    secret:
        key: ${JWT_SECRET:BvdCDROpy/QRNPizw10GXalXzl41f/YOK2SfJNK2s+w=}